#+TITLE: Angular Learning Resources
#+AUTHOR: Joaquim Gregório da Silva Neto

* Basics
** Create a new project
#+begin_src sh
npm install --location=global @angular/cli
#+end_src
- Now you can create a new project
  #+begin_src sh
ng new <project-name>
  #+end_src
- You can add css libraries to angular by installing it and importing the css file in the ~styles~ section in *angular.json* file.
- First add the library (bootstrap in this example):
  #+begin_src sh
yarn add bootstrap
  #+end_src
- Now, in the *angular.json* file:
  #+begin_src json
"styles": [
    "node_modules/bootstrap/dist/css/bootstrap.min.css",
    "src/styles.css"
]
  #+end_src
** Components
- Components are created by using the **Component** decorator from **'@angular/core'**, the you must register the component in the module of the nearest component module:
~user.component.ts~
  #+begin_src typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
})
export class UserComponent {}
  #+end_src
~app.module.ts~
#+begin_src typescript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';
import { UserComponent } from './user/user.component';

@NgModule({
  declarations: [AppComponent, UserComponent],
  imports: [BrowserModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
#+end_src
- You can also set the **selector**, **template** or **templateUrl** and **styles** or **styleUrl** as properties in the **Component** decorator.
- The selector defines the way you use the component. Since the selector is just 'app-user', you will use the component as a common html tag.  
